shamefullyHoist: true

packages:
  - packages/*

catalog:
  "@antfu/eslint-config": ^4.13.2
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/scripts": ^0.0.2
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  eslint: ^9.27.0
  tsdown: ^0.12.1
  vitest: ^3.1.4
  xml-formatter: ^3.6.6

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
