shamefullyHoist: true

packages:
  - packages/*

catalog:
  "@antfu/eslint-config": ^4.13.1
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  eslint: ^9.26.0
  fast-xml-parser: ^5.2.3
  tsdown: ^0.11.9
  vitest: ^3.1.3

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
