shamefullyHoist: true

packages:
  - packages/*

catalog:
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/scripts": ^0.0.3
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.3
  eslint: ^9.35.0
  tsdown: ^0.15.2
  vitest: ^3.2.4
  xml-formatter: ^3.6.7

onlyBuiltDependencies:
  - esbuild
  - rolldown
